from backend.app.agents.base import BaseAgent

class ExecutorAgent(BaseAgent):
    def __init__(self):
        super().__init__(
            name="Executor",
            system_instruction=(
                "You are the Lead Execution Agent. Your job is to create the actual final product. "
                "This could be writing production-quality code, formatting detailed reports, creating tables, "
                "or building implementation guides. Focus on structure, clarity, proper formatting, and execution detail. "
                "Ensure your outputs are comprehensive and ready to be delivered to the client."
            )
        )

    async def run_subtask(self, subtask_title: str, subtask_desc: str, context: str, task_id: str, subtask_id: str) -> str:
        # Detect whether this is a coding or business/research task
        task_lower = (subtask_title + " " + subtask_desc).lower()
        is_code_task = any(w in task_lower for w in [
            "code", "debug", "error", "bug", "fix", "implement", "script",
            "function", "class", "program", "python", "javascript", "lint", "syntax"
        ])

        if is_code_task:
            mock_execution_output = (
                f"# Code Solution: {subtask_title}\n\n"
                f"> **Task:** {subtask_desc}\n\n"
                "## Implementation\n\n"
                "The root cause was identified by the Reasoning Agent. Below is the corrected implementation:\n\n"
                "```python\n"
                f"# Solution for: {subtask_title}\n"
                "# Generated by AgentForge Executor — Software Debugging Suite\n\n"
                "from typing import Optional, List\n\n"
                "class SafeStack:\n"
                "    \"\"\"Thread-safe stack with bounds checking and descriptive error handling.\"\"\"\n\n"
                "    def __init__(self, max_size: int = 1000):\n"
                "        self._items: List = []\n"
                "        self.max_size = max_size\n\n"
                "    def push(self, item) -> None:\n"
                "        \"\"\"Push an item onto the stack.\"\"\"\n"
                "        if len(self._items) >= self.max_size:\n"
                "            raise OverflowError(f'Stack overflow: max size {self.max_size} reached.')\n"
                "        self._items.append(item)\n\n"
                "    def pop(self) -> any:\n"
                "        \"\"\"Pop and return the top item. Raises ValueError on empty stack.\"\"\"\n"
                "        if not self._items:\n"
                "            raise ValueError('Stack underflow: cannot pop from an empty stack.')\n"
                "        return self._items.pop()\n\n"
                "    def peek(self) -> any:\n"
                "        \"\"\"Return top item without removing it.\"\"\"\n"
                "        if not self._items:\n"
                "            raise ValueError('Stack is empty.')\n"
                "        return self._items[-1]\n\n"
                "    @property\n"
                "    def is_empty(self) -> bool:\n"
                "        return len(self._items) == 0\n\n"
                "    def __len__(self) -> int:\n"
                "        return len(self._items)\n\n\n"
                "# --- Usage Example ---\n"
                "if __name__ == '__main__':\n"
                "    stack = SafeStack()\n"
                "    stack.push(10)\n"
                "    stack.push(20)\n"
                "    print(stack.pop())   # → 20\n"
                "    print(stack.peek())  # → 10\n"
                "    print(stack.pop())   # → 10\n"
                "    try:\n"
                "        stack.pop()  # → Raises ValueError\n"
                "    except ValueError as e:\n"
                "        print(f'Caught error: {e}')\n"
                "```\n\n"
                "## Explanation of Fix\n\n"
                "| Issue | Root Cause | Fix Applied |\n"
                "|-------|-----------|-------------|\n"
                "| `IndexError` on empty pop | No guard before `list.pop()` | Added `if not self._items` check |\n"
                "| Silent overflow | No max-size enforcement | Added `max_size` cap with `OverflowError` |\n"
                "| Poor error messages | Generic Python exceptions | Custom, descriptive error strings |\n\n"
                "## SOLID Compliance Review\n"
                "- ✅ **Single Responsibility**: `SafeStack` handles only stack operations.\n"
                "- ✅ **Open/Closed**: Extendable via subclassing without modifying core logic.\n"
                "- ✅ **Liskov Substitution**: Conforms to standard stack interface contracts.\n"
                "- ✅ **Dependency Inversion**: No tight coupling to external frameworks.\n"
            )
        else:
            mock_execution_output = (
                f"# Strategic Report: {subtask_title}\n\n"
                f"> **Compiled by AgentForge Executor** | Based on research & reasoning layers\n\n"
                f"## 1. Executive Summary\n"
                f"This report addresses: **{subtask_desc}**\n\n"
                "The analysis draws on market intelligence, competitor profiling, and strategic SWOT analysis "
                "to deliver actionable insights. The following sections present findings in order of strategic importance.\n\n"
                "## 2. Market Opportunity Assessment\n\n"
                "| Metric | Value | Source |\n"
                "|--------|-------|--------|\n"
                "| Total Addressable Market (TAM) | $18.4B by 2028 | McKinsey AI Report 2024 |\n"
                "| CAGR (2024–2028) | 38.2% | Gartner Hype Cycle 2024 |\n"
                "| Enterprise Adoption Rate | 64% YoY increase | a16z AI Canon |\n"
                "| Open-source Contribution Growth | 150%+ YoY | GitHub Trending |\n\n"
                "## 3. Competitive Landscape\n\n"
                "### Tier-1 Competitors\n"
                "**Competitor A** — Commands ~24% market share via aggressive enterprise pricing. "
                "Weakness: poor extensibility, locked-in ecosystem.\n\n"
                "**Competitor B** — Usage-based SaaS with strong developer experience. "
                "Weakness: high cost at scale, no on-premise option.\n\n"
                "**Competitor C** — Open-source community leader. "
                "Weakness: no dedicated support tier, limited enterprise integrations.\n\n"
                "## 4. SWOT Matrix\n\n"
                "| | **Strengths** | **Weaknesses** |\n"
                "|-|--------------|----------------|\n"
                "| **Internal** | First-mover in agentic pipelines; modular plugin system; LangGraph-native | Rate limits on free API tiers; SQLite not production-grade |\n"
                "| | **Opportunities** | **Threats** |\n"
                "| **External** | Surging enterprise demand; MCP ecosystem as free distribution channel | OpenAI/Anthropic native orchestration tools; commoditization of LLMs |\n\n"
                "## 5. Strategic Execution Roadmap\n\n"
                "```\n"
                "Phase 1 (Q1–Q2 2025) ─── MVP Launch\n"
                "  ├── SQLite DB with 3 core plugins\n"
                "  ├── Gemini 2.5-Flash powered agents\n"
                "  └── MCP local server support\n\n"
                "Phase 2 (Q3–Q4 2025) ─── SaaS Hardening\n"
                "  ├── PostgreSQL migration + Redis caching\n"
                "  ├── OAuth 2.0 user authentication\n"
                "  └── Docker-sandboxed MCP subprocess isolation\n\n"
                "Phase 3 (2026) ─────── Enterprise Scale\n"
                "  ├── Kubernetes HA deployment\n"
                "  ├── Custom fine-tuned reasoning models\n"
                "  └── SOC2 / GDPR compliance certification\n"
                "```\n\n"
                "## 6. Risk Register\n\n"
                "| Risk | Likelihood | Impact | Mitigation |\n"
                "|------|-----------|--------|------------|\n"
                "| LLM API rate limits | High | High | Implement retry logic + fallback mock layer |\n"
                "| Data freshness | Medium | Medium | Schedule Tavily re-crawls weekly |\n"
                "| Competitor feature parity | Medium | High | Invest in plugin extensibility R&D |\n"
                "| Security breach via MCP subprocess | Low | Critical | Containerize all third-party MCP servers |\n"
            )

        output = await self.execute_llm(
            prompt=(
                f"You have been assigned the subtask: {subtask_title}\n"
                f"Subtask Details: {subtask_desc}\n\n"
                f"Here is the context and previous agent reasoning to build upon:\n"
                f"{context}\n\n"
                "Please generate the complete, finalized output for this subtask. "
                "Ensure it is rich, descriptive, and formatted in markdown."
            ),
            task_id=task_id,
            subtask_id=subtask_id,
            mock_response_content=mock_execution_output
        )
        return output
