"""
export.py — Deliverable export endpoints for AgentForge tasks.

Supported formats:
  GET /api/tasks/{task_id}/export?format=md   -> raw Markdown file
  GET /api/tasks/{task_id}/export?format=pdf  -> PDF (via reportlab)
  GET /api/tasks/{task_id}/export?format=zip  -> ZIP of extracted code files + report
"""

import io
import re
import zipfile
from datetime import datetime

from fastapi import APIRouter, Depends, HTTPException, Query
from fastapi.responses import Response
from sqlalchemy.orm import Session

from backend.app.database.connection import get_db
from backend.app.database.models import Task, Subtask

router = APIRouter(prefix="/tasks", tags=["export"])

# ---------------------------------------------------------------------------
# Constants / helpers
# ---------------------------------------------------------------------------

_CODE_FENCE_RE = re.compile(
    r"```(?P<lang>[a-zA-Z0-9_+\-\.]*)\n(?P<code>.*?)```",
    re.DOTALL,
)

_EXT_MAP = {
    "python": "py", "py": "py",
    "javascript": "js", "js": "js",
    "typescript": "ts", "ts": "ts",
    "tsx": "tsx", "jsx": "jsx",
    "bash": "sh", "sh": "sh", "shell": "sh",
    "sql": "sql",
    "yaml": "yaml", "yml": "yaml",
    "json": "json",
    "html": "html",
    "css": "css",
    "go": "go",
    "rust": "rs",
    "java": "java",
    "c": "c", "cpp": "cpp",
    "markdown": "md", "md": "md",
    "dockerfile": "dockerfile",
    "text": "txt", "": "txt",
}


def _sanitise_filename(name: str) -> str:
    return re.sub(r"[^\w\-.]", "_", name)


def _extract_code_blocks(content: str) -> list:
    """Return list of {lang, code, filename} dicts from fenced code blocks."""
    blocks = []
    counters: dict = {}
    for match in _CODE_FENCE_RE.finditer(content):
        lang = match.group("lang").strip().lower()
        code = match.group("code")
        ext = _EXT_MAP.get(lang, "txt")
        counters[ext] = counters.get(ext, 0) + 1
        idx = counters[ext]
        filename = f"file_{idx}.{ext}" if ext != "txt" else f"snippet_{idx}.txt"
        blocks.append({"lang": lang, "code": code, "filename": filename})
    return blocks


# ---------------------------------------------------------------------------
# Markdown builder
# ---------------------------------------------------------------------------

def _build_markdown(task, subtasks) -> str:
    ts = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    lines = [
        "# AgentForge Deliverable Report",
        "",
        f"> **Task ID:** `{task.id}`  ",
        f"> **Generated:** {ts}  ",
        f"> **Plugin:** `{task.plugin_name}`  ",
        f"> **Status:** `{task.status}`  ",
        "",
        "---",
        "",
        "## Objective",
        "",
        task.prompt or "_No prompt recorded._",
        "",
    ]

    if subtasks:
        lines += ["---", "", "## Execution Plan", ""]
        for i, st in enumerate(subtasks, 1):
            agent = st.assigned_agent or "unknown"
            status = st.status or "pending"
            conf = f"{round(st.confidence_score * 100)}%" if st.confidence_score else "N/A"
            lines.append(f"### {i}. {st.title}")
            lines.append("")
            if st.description:
                lines.append(f"_{st.description}_")
                lines.append("")
            lines.append(
                f"| Field | Value |\n|-------|-------|\n"
                f"| Agent | `{agent}` |\n"
                f"| Status | `{status}` |\n"
                f"| Confidence | `{conf}` |"
            )
            lines.append("")
            if st.output:
                lines.append("**Agent Output:**")
                lines.append("")
                lines.append(st.output)
                lines.append("")

    lines += [
        "---",
        "",
        "## Verified Deliverable",
        "",
        task.final_result or "_No result generated yet._",
        "",
        "---",
        "",
        f"_Report generated by AgentForge \u2022 {ts}_",
    ]

    if task.total_tokens or task.total_cost_usd is not None:
        lines += ["", "### Telemetry", "", "| Metric | Value |", "|--------|-------|"]
        if task.total_tokens:
            lines.append(f"| Total Tokens | `{task.total_tokens:,}` |")
        if task.total_cost_usd is not None:
            lines.append(f"| Estimated Cost | `${task.total_cost_usd:.4f}` |")
        if task.total_latency_ms is not None:
            lines.append(f"| Total Latency | `{task.total_latency_ms:,} ms` |")

    return "\n".join(lines)


# ---------------------------------------------------------------------------
# PDF builder
# ---------------------------------------------------------------------------

def _build_pdf(task, subtasks, md_content: str) -> bytes:
    from reportlab.lib.pagesizes import A4
    from reportlab.lib.units import cm
    from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
    from reportlab.lib import colors
    from reportlab.platypus import (
        SimpleDocTemplate, Paragraph, Spacer, HRFlowable, Preformatted, Table, TableStyle,
    )

    ACCENT = colors.HexColor("#da7756")
    CODE_BG = colors.HexColor("#121214")
    TEXT_DIM = colors.HexColor("#d4d4d8")
    TEXT_MUTED = colors.HexColor("#a1a1aa")

    buf = io.BytesIO()
    doc = SimpleDocTemplate(
        buf, pagesize=A4,
        leftMargin=2 * cm, rightMargin=2 * cm,
        topMargin=2 * cm, bottomMargin=2 * cm,
    )
    styles = getSampleStyleSheet()

    s_title = ParagraphStyle("s_title", parent=styles["Heading1"], fontSize=22,
                             textColor=ACCENT, spaceAfter=6, fontName="Helvetica-Bold")
    s_h2 = ParagraphStyle("s_h2", parent=styles["Heading2"], fontSize=14,
                          textColor=ACCENT, spaceBefore=14, spaceAfter=4, fontName="Helvetica-Bold")
    s_h3 = ParagraphStyle("s_h3", parent=styles["Heading3"], fontSize=12,
                          textColor=colors.HexColor("#e0e0e0"), spaceBefore=10,
                          spaceAfter=3, fontName="Helvetica-Bold")
    s_body = ParagraphStyle("s_body", parent=styles["Normal"], fontSize=10,
                            textColor=TEXT_DIM, spaceAfter=6, leading=15, fontName="Helvetica")
    s_meta = ParagraphStyle("s_meta", parent=styles["Normal"], fontSize=8,
                            textColor=TEXT_MUTED, spaceAfter=3, fontName="Helvetica-Oblique")
    s_code = ParagraphStyle("s_code", parent=styles["Code"], fontSize=8,
                            textColor=colors.HexColor("#86efac"), backColor=CODE_BG,
                            fontName="Courier", leading=12, spaceAfter=8)

    ts_str = datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")
    story = []

    story.append(Paragraph("AgentForge Deliverable Report", s_title))
    story.append(HRFlowable(width="100%", thickness=1, color=ACCENT, spaceAfter=6))

    meta_rows = [
        ["Task ID", task.id],
        ["Generated", ts_str],
        ["Plugin", task.plugin_name],
        ["Status", task.status],
    ]
    if task.total_tokens:
        meta_rows.append(["Total Tokens", f"{task.total_tokens:,}"])
    if task.total_cost_usd is not None:
        meta_rows.append(["Est. Cost", f"${task.total_cost_usd:.4f}"])

    meta_tbl = Table(meta_rows, colWidths=[4 * cm, 12 * cm])
    meta_tbl.setStyle(TableStyle([
        ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("TEXTCOLOR", (0, 0), (0, -1), ACCENT),
        ("TEXTCOLOR", (1, 0), (1, -1), TEXT_DIM),
        ("ROWBACKGROUNDS", (0, 0), (-1, -1),
         [colors.HexColor("#1c1c1f"), colors.HexColor("#18181b")]),
        ("BOTTOMPADDING", (0, 0), (-1, -1), 4),
        ("TOPPADDING", (0, 0), (-1, -1), 4),
        ("LEFTPADDING", (0, 0), (-1, -1), 6),
    ]))
    story.append(meta_tbl)
    story.append(Spacer(1, 12))

    story.append(Paragraph("Objective", s_h2))
    prompt_safe = (task.prompt or "_No prompt._").replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
    story.append(Paragraph(prompt_safe, s_body))

    if subtasks:
        story.append(Paragraph("Execution Plan", s_h2))
        story.append(HRFlowable(width="100%", thickness=0.5,
                                color=colors.HexColor("#3f3f46"), spaceAfter=4))
        for i, st in enumerate(subtasks, 1):
            story.append(Paragraph(f"{i}. {st.title}", s_h3))
            if st.description:
                story.append(Paragraph(st.description, s_meta))
            conf = f"{round(st.confidence_score * 100)}%" if st.confidence_score else "N/A"
            sub_tbl = Table(
                [["Agent", st.assigned_agent or "N/A", "Status", st.status or "pending"],
                 ["Confidence", conf, "", ""]],
                colWidths=[3 * cm, 5 * cm, 3 * cm, 5 * cm],
            )
            sub_tbl.setStyle(TableStyle([
                ("FONTNAME", (0, 0), (-1, -1), "Helvetica"),
                ("FONTSIZE", (0, 0), (-1, -1), 8),
                ("TEXTCOLOR", (0, 0), (0, -1), ACCENT),
                ("TEXTCOLOR", (2, 0), (2, -1), ACCENT),
                ("TEXTCOLOR", (1, 0), (-1, -1), TEXT_DIM),
                ("BACKGROUND", (0, 0), (-1, -1), colors.HexColor("#1c1c1f")),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 3),
                ("TOPPADDING", (0, 0), (-1, -1), 3),
                ("LEFTPADDING", (0, 0), (-1, -1), 6),
            ]))
            story.append(sub_tbl)
            story.append(Spacer(1, 4))

    story.append(Paragraph("Verified Deliverable", s_h2))
    story.append(HRFlowable(width="100%", thickness=0.5, color=ACCENT, spaceAfter=6))

    final = task.final_result or "_No result generated yet._"
    last_end = 0
    for m in _CODE_FENCE_RE.finditer(final):
        pre = final[last_end:m.start()].strip()
        if pre:
            for line in pre.split("\n"):
                l = line.strip()
                if not l:
                    story.append(Spacer(1, 4))
                    continue
                safe = l.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
                if l.startswith("### "):
                    story.append(Paragraph(safe[4:], s_h3))
                elif l.startswith("## ") or l.startswith("# "):
                    story.append(Paragraph(safe.lstrip("# "), s_h2))
                elif l.startswith("- ") or l.startswith("* "):
                    story.append(Paragraph(f"\u2022 {safe[2:]}", s_body))
                else:
                    story.append(Paragraph(safe, s_body))
        lang = m.group("lang").strip() or "text"
        code = m.group("code")[:3000]  # cap very long blocks
        story.append(Paragraph(f"[ {lang} ]", s_meta))
        story.append(Preformatted(code, s_code))
        last_end = m.end()

    tail = final[last_end:].strip()
    if tail:
        for line in tail.split("\n"):
            l = line.strip()
            if not l:
                story.append(Spacer(1, 4))
                continue
            safe = l.replace("&", "&amp;").replace("<", "&lt;").replace(">", "&gt;")
            if l.startswith("### "):
                story.append(Paragraph(safe[4:], s_h3))
            elif l.startswith("## ") or l.startswith("# "):
                story.append(Paragraph(safe.lstrip("# "), s_h2))
            elif l.startswith("- ") or l.startswith("* "):
                story.append(Paragraph(f"\u2022 {safe[2:]}", s_body))
            else:
                story.append(Paragraph(safe, s_body))

    story.append(Spacer(1, 16))
    story.append(HRFlowable(width="100%", thickness=0.5,
                            color=colors.HexColor("#3f3f46"), spaceAfter=4))
    story.append(Paragraph(f"Generated by AgentForge \u2022 {ts_str}", s_meta))

    doc.build(story)
    buf.seek(0)
    return buf.read()


# ---------------------------------------------------------------------------
# ZIP builder
# ---------------------------------------------------------------------------

def _build_zip(task, subtasks, md_content: str) -> bytes:
    buf = io.BytesIO()
    code_blocks = _extract_code_blocks(task.final_result or "")

    with zipfile.ZipFile(buf, mode="w", compression=zipfile.ZIP_DEFLATED) as zf:
        zf.writestr("REPORT.md", md_content.encode("utf-8"))

        readme_lines = [
            f"# AgentForge Export — {task.id}",
            "",
            f"**Prompt:** {task.prompt}",
            f"**Plugin:** {task.plugin_name}",
            f"**Generated:** {datetime.utcnow().strftime('%Y-%m-%d %H:%M UTC')}",
            "",
            "## Files",
            "",
            "- `REPORT.md` — Full verified deliverable report",
        ]

        if code_blocks:
            readme_lines.append(f"- `code/` — Extracted code files ({len(code_blocks)} files)")
            seen: dict = {}
            for block in code_blocks:
                raw_name = block["filename"]
                if raw_name in seen:
                    seen[raw_name] += 1
                    parts = raw_name.rsplit(".", 1)
                    raw_name = f"{parts[0]}_{seen[raw_name]}.{parts[1]}" if len(parts) == 2 else f"{raw_name}_{seen[raw_name]}"
                else:
                    seen[raw_name] = 1
                zf.writestr(f"code/{raw_name}", block["code"].encode("utf-8"))

        if subtasks:
            readme_lines.append("- `subtasks/` — Individual subtask agent outputs")
            for i, st in enumerate(subtasks, 1):
                if st.output:
                    fname = _sanitise_filename(st.title[:50]) or f"subtask_{i}"
                    zf.writestr(f"subtasks/{i:02d}_{fname}.md", st.output.encode("utf-8"))

        zf.writestr("README.md", "\n".join(readme_lines).encode("utf-8"))

    buf.seek(0)
    return buf.read()


# ---------------------------------------------------------------------------
# Endpoint
# ---------------------------------------------------------------------------

@router.get("/{task_id}/export")
def export_task(
    task_id: str,
    format: str = Query("md", description="Export format: md | pdf | zip"),
    db: Session = Depends(get_db),
):
    """Export a task deliverable as Markdown, PDF, or ZIP archive."""
    if format not in ("md", "pdf", "zip"):
        raise HTTPException(status_code=400, detail="format must be one of: md, pdf, zip")

    task = db.query(Task).filter(Task.id == task_id).first()
    if not task:
        raise HTTPException(status_code=404, detail="Task not found")

    subtasks = (
        db.query(Subtask)
        .filter(Subtask.task_id == task_id)
        .order_by(Subtask.order_index.asc())
        .all()
    )

    safe_id = task_id[:8]
    timestamp = datetime.utcnow().strftime("%Y%m%d_%H%M")
    md_content = _build_markdown(task, subtasks)

    if format == "md":
        filename = f"agentforge_{safe_id}_{timestamp}.md"
        return Response(
            content=md_content.encode("utf-8"),
            media_type="text/markdown",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    elif format == "pdf":
        try:
            pdf_bytes = _build_pdf(task, subtasks, md_content)
        except ImportError:
            raise HTTPException(
                status_code=501,
                detail="PDF export requires reportlab. Run: pip install 'reportlab>=4.0.0'",
            )
        filename = f"agentforge_{safe_id}_{timestamp}.pdf"
        return Response(
            content=pdf_bytes,
            media_type="application/pdf",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )

    else:  # zip
        zip_bytes = _build_zip(task, subtasks, md_content)
        filename = f"agentforge_{safe_id}_{timestamp}.zip"
        return Response(
            content=zip_bytes,
            media_type="application/zip",
            headers={"Content-Disposition": f'attachment; filename="{filename}"'},
        )
